# Generated by Django 3.2.6 on 2021-08-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el objeto ha sido eliminado o no.')),
                ('deleted_at', models.DateTimeField(help_text='Día y hora en que se eliminó el objeto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Día y hora de creación del objeto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Día y hora de modificación del objeto')),
                ('row_count', models.PositiveSmallIntegerField()),
                ('column_count', models.PositiveSmallIntegerField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('rest_time', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'theatre',
                'verbose_name_plural': 'theatres',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el objeto ha sido eliminado o no.')),
                ('deleted_at', models.DateTimeField(help_text='Día y hora en que se eliminó el objeto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Día y hora de creación del objeto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Día y hora de modificación del objeto')),
                ('schedule', models.DateTimeField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.screening')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre')),
            ],
            options={
                'verbose_name': 'show',
                'verbose_name_plural': 'shows',
                'ordering': ['theatre', 'screening', 'schedule'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si el objeto ha sido eliminado o no.')),
                ('deleted_at', models.DateTimeField(help_text='Día y hora en que se eliminó el objeto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Día y hora de creación del objeto')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Día y hora de modificación del objeto')),
                ('row', models.CharField(max_length=1)),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('1', 'Libre'), ('2', 'Reservado'), ('3', 'Vendido')], default='1', max_length=1)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatres.theatre')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'ordering': ['theatre', 'id'],
            },
        ),
    ]
